import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "sw";

interface Translations {
  [key: string]: {
    en: string;
    sw: string;
  };
}

export const translations: Translations = {
  // Navigation
  "nav.home": { en: "Home", sw: "Nyumbani" },
  "nav.about": { en: "About", sw: "Kuhusu" },
  "nav.academics": { en: "Academics", sw: "Masomo" },
  "nav.facilities": { en: "Facilities", sw: "Vifaa" },
  "nav.news": { en: "News", sw: "Habari" },
  "nav.contact": { en: "Contact", sw: "Wasiliana" },
  "nav.studentLife": { en: "Student Life", sw: "Maisha ya Mwanafunzi" },
  "nav.apply": { en: "Apply Now", sw: "Omba Sasa" },
  "nav.login": { en: "Login", sw: "Ingia" },
  "nav.services": { en: "Services", sw: "Huduma" },
  "nav.vision": { en: "Our Vision", sw: "Maono Yetu" },
  "nav.mission": { en: "Our Mission", sw: "Dhamira Yetu" },
  "nav.admissions": { en: "Admissions", sw: "Usajili" },
  "nav.students": { en: "Students", sw: "Wanafunzi" },
  "nav.staff": { en: "Staff", sw: "Wafanyakazi" },
  "nav.gallery": { en: "Gallery", sw: "Picha" },
  "nav.sports": { en: "Sports", sw: "Michezo" },
  "nav.arts": { en: "Arts", sw: "Sanaa" },
  "nav.alumni": { en: "Alumni", sw: "Wahitimu" },
  "nav.results": { en: "Exam Results", sw: "Matokeo ya Mitihani" },

  // Hero Section
  "hero.excellence": { en: "Excellence.", sw: "Ubora." },
  "hero.tradition": { en: "Defined by Tradition.", sw: "Inayotokana na Mapokeo." },
  "hero.innovation": { en: "Innovation.", sw: "Uvumbuzi." },
  "hero.brightestMinds": { en: "For the Brightest Minds.", sw: "Kwa Akili Changamfu Zaidi." },
  "hero.character": { en: "Character.", sw: "Tabia." },
  "hero.futureLeaders": { en: "Shaping Future Leaders.", sw: "Kuunda Viongozi wa Kesho." },
  "hero.apply2026": { en: "Apply for 2026", sw: "Omba kwa Mwaka 2026" },
  "hero.watchFilm": { en: "Watch the Film", sw: "Tazama Filamu" },
  "hero.discover": { en: "Discover Sacred Heart", sw: "Gundua Sacred Heart" },
  "hero.scroll": { en: "Scroll to explore", sw: "Sogeza kutazama" },
  "hero.students": { en: "Students", sw: "Wanafunzi" },
  "hero.teachers": { en: "Qualified Teachers", sw: "Walimu Waliohitimu" },
  "hero.passRate": { en: "Pass Rate", sw: "Kiwango cha Kufaulu" },
  "hero.yearsExcellence": { en: "Years of Excellence", sw: "Miaka ya Ubora" },
  "hero.nationalStandards": { en: "National Standards", sw: "Viwango vya Kitaifa" },

  // Why Choose Us
  "why.badge": { en: "Why Choose Us", sw: "Kwanini Utuchague" },
  "why.title": { en: "Excellence in Every Dimension.", sw: "Ubora katika Kila Nyanja." },
  "why.desc": { en: "We don't just teach students; we transform them into global leaders who are ready to make a difference.", sw: "Hatufundishi wanafunzi tu; tunawabadilisha kuwa viongozi wa kimataifa ambao wako tayari kuleta mabadiliko." },
  "why.safe.title": { en: "Safe & Serene Environment", sw: "Mazingira Salama na Matulivu" },
  "why.safe.desc": { en: "Located away from city noise, providing a perfect atmosphere for focused learning.", sw: "Iko mbali na kelele za mji, ikitoa mazingira bora kwa ajili ya kujifunza kwa uangalifu." },
  "why.academic.title": { en: "Academic Rigor", sw: "Ukali wa Kitaaluma" },
  "why.academic.desc": { en: "Our curriculum is designed to challenge students and prepare them for world-class universities.", sw: "Mitaala yetu imeundwa ili kuwapa changamoto wanafunzi na kuwaandaa kwa vyuo vikuu vya kiwango cha kimataifa." },
  "why.character.title": { en: "Character Building", sw: "Jengo la Tabia" },
  "why.character.desc": { en: "We focus on integrity, discipline, and leadership skills that stay for a lifetime.", sw: "Tunazingatia uadilifu, nidhamu, na ujuzi wa uongozi unaodumu kwa maisha yote." },
  "why.holistic.title": { en: "Holistic Development", sw: "Maendeleo ya Jumla" },
  "why.holistic.desc": { en: "Strong emphasis on arts, sports, and community service alongside traditional academics.", sw: "Msisitizo mkubwa juu ya sanaa, michezo, na huduma kwa jamii pamoja na taaluma za jadi." },
  "why.facilities.title": { en: "Modern Facilities", sw: "Vifaa vya Kisasa" },
  "why.facilities.desc": { en: "High-tech labs, extensive library, and digital classrooms supporting 21st-century learning.", sw: "Maabara za hali ya juu, maktaba pana, na madarasa ya kidijitali yanayosaidia kujifunza kwa karne ya 21." },
  "why.mentorship.title": { en: "Dedicated Mentorship", sw: "Ushauri wa Kujitolea" },
  "why.mentorship.desc": { en: "Our teachers are more than instructors; they are mentors committed to every student's success.", sw: "Walimu wetu ni zaidi ya wakufunzi; ni washauri waliojitolea kwa mafanikio ya kila mwanafunzi." },

  // Stats
  "stats.students": { en: "Students", sw: "Wanafunzi" },
  "stats.faculty": { en: "Expert Teachers", sw: "Walimu Wataalamu" },
  "stats.success": { en: "Exam Pass Rate", sw: "Kiwango cha Kufaulu" },
  "stats.years": { en: "Years of Excellence", sw: "Miaka ya Ubora" },

  // Academics
  "academics.badge": { en: "Our Academic Programs", sw: "Mipango yetu ya Kitaaluma" },
  "academics.title": { en: "Excellence Across Every Stage.", sw: "Ubora katika Kila Hatua." },
  "academics.desc": { en: "We provide a continuous educational journey from early childhood to secondary level, fostering growth at every step.", sw: "Tunatoa safari ya elimu inayoendelea kutoka utotoni hadi kiwango cha sekondari." },
  "academics.nursery": { en: "SIIMA Nursery School", sw: "Shule ya Chekechea ya SIIMA" },
  "academics.nursery.desc": { en: "Nurturing curiosity and social skills at SIIMA Primary School (Nursery Section).", sw: "Kukuza udadisi na stadi za kijamii katika Shule ya SIIMA (Chekechea)." },
  "academics.primary": { en: "SIIMA Primary School", sw: "Shule ya Msingi ya SIIMA" },
  "academics.primary.desc": { en: "Building a strong foundation at SIIMA Primary from Standard 1 to Standard 7.", sw: "Kujenga msingi imara SIIMA kuanzia Darasa la 1 hadi la 7." },
  "academics.secondary": { en: "Sacred Heart Secondary", sw: "Sekondari ya Sacred Heart" },
  "academics.secondary.desc": { en: "Preparing students for global success at Sacred Heart Secondary (Form 1 - Form 4).", sw: "Kuandaa wanafunzi kwa mafanikio ya kimataifa Sacred Heart (Kidato cha 1 - 4)." },
  "academics.readMore": { en: "Read More", sw: "Soma Zaidi" },

  // Team Section
  "team.badge": { en: "Our Team", sw: "Timu Yetu" },
  "team.title": { en: "Meet Our Educators", sw: "Kutana na Walimu Wetu" },
  "team.desc": { en: "A dedicated team of professionals committed to helping every student reach their full potential.", sw: "Timu ya wataalamu iliyojitolea kusaidia kila mwanafunzi kufikia uwezo wao kamili." },
  "team.head": { en: "Head Teacher", sw: "Mwalimu Mkuu" },
  "team.academic": { en: "Academic Dean", sw: "Mkuu wa Taaluma" },
  "team.humanities": { en: "Head of Humanities", sw: "Mkuu wa Masomo ya Jamii" },
  "team.administration": { en: "School Administration", sw: "Utawala wa Shule" },

  // Staff Page
  "staff.hero.title": { en: "Our Staff", sw: "Wafanyakazi Wetu" },
  "staff.hero.subtitle": { en: "Meet the dedicated team of educators shaping the future leaders of Tanzania", sw: "Kutana na timu ya waelimishaji waliojitolea wanaounda viongozi wa kesho wa Tanzania" },
  "staff.stats.totalTeachers": { en: "Total Teachers", sw: "Jumla ya Walimu" },
  "staff.stats.phd": { en: "PhD Holders", sw: "Wenye PhD" },
  "staff.stats.masters": { en: "Masters Holders", sw: "Wenye Masters" },
  "staff.stats.support": { en: "Support Staff", sw: "Wafanyakazi wa Huduma" },
  "staff.admin.title": { en: "School Administration", sw: "Utawala wa Shule" },
  "staff.admin.subtitle": { en: "Leadership team guiding Sacred Heart towards excellence", sw: "Timu ya uongozi inayoongoza Sacred Heart kuelekea ubora" },
  "staff.teachers.title": { en: "Our Teachers", sw: "Walimu Wetu" },
  "staff.teachers.subtitle": { en: "Dedicated educators committed to nurturing academic excellence", sw: "Waelimishaji waliojitolea kukuza ubora wa kitaaluma" },
  "staff.search.placeholder": { en: "Search by name, subject, or specialization...", sw: "Tafuta kwa jina, somo, au utaalamu..." },
  "staff.filter.button": { en: "Filter", sw: "Chuja" },
  "staff.filter.dept": { en: "Department / Subject", sw: "Idara / Somo" },
  "staff.filter.clear": { en: "Clear all", sw: "Futa yote" },
  "staff.profile.view": { en: "View Profile", sw: "Tazama Maelezo" },
  "staff.noResults.title": { en: "No teachers found", sw: "Hakuna walimu waliopatikana" },
  "staff.noResults.desc": { en: "Try adjusting your search or filter criteria", sw: "Jaribu kurekebisha utafutaji wako au vigezo vya chujio" },
  "staff.join.title": { en: "Join Our Team", sw: "Jiunge na Timu Yetu" },
  "staff.join.desc": { en: "We're always looking for passionate educators to join Sacred Heart. Check our current openings or send your CV.", sw: "Daima tunatafuta waelimishaji wenye upendo wa kujiunga na Sacred Heart. Angalia nafasi zetu za sasa au tuma CV yako." },
  "staff.join.viewOpenings": { en: "View Openings", sw: "Tazama Nafasi" },
  "staff.join.sendCV": { en: "Send CV", sw: "Tuma CV" },
  "staff.filter.all": { en: "All", sw: "Zote" },
  "staff.filter.mathematics": { en: "Mathematics", sw: "Hisabati" },
  "staff.filter.sciences": { en: "Sciences", sw: "Sayansi" },
  "staff.filter.languages": { en: "Languages", sw: "Lugha" },
  "staff.filter.humanities": { en: "Humanities", sw: "Masomo ya Jamii" },
  "staff.filter.artsSports": { en: "Arts & Sports", sw: "Sanaa na Michezo" },

  // Contact Section
  "contact.badge": { en: "Contact Us", sw: "Wasiliana Nasi" },
  "contact.title": { en: "Get in Touch", sw: "Wasiliana Nasi" },
  "contact.desc": { en: "Have questions? We're here to help. Reach out to us through any of the channels below.", sw: "Una maswali? Tuko hapa kusaidia. Wasiliana nasi kupitia njia yoyote hapa chini." },
  "contact.form.name": { en: "Full Name", sw: "Jina Kamili" },
  "contact.form.email": { en: "Email Address", sw: "Barua Pepe" },
  "contact.form.subject": { en: "Subject", sw: "Mada" },
  "contact.form.message": { en: "Your Message", sw: "Ujumbe Wako" },
  "contact.form.send": { en: "Send Message", sw: "Tuma Ujumbe" },
  "contact.info.title": { en: "Contact Information", sw: "Habari za Mawasiliano" },
  "contact.map.title": { en: "Find Us Here", sw: "Tupate Hapa" },
  "contact.address": { en: "Address", sw: "Anwani" },
  "contact.phone": { en: "Phone", sw: "Simu" },
  "contact.email": { en: "Email", sw: "Barua Pepe" },
  "contact.hours": { en: "Hours", sw: "Muda" },
  "contact.hoursValue": { en: "Mon - Fri, 8am - 4pm", sw: "Jumatatu - Ijumaa, Saa 2 asubuhi - Saa 10 jioni" },
  "contact.form.write": { en: "Write to us", sw: "Tuandikie" },
  "contact.form.respond": { en: "We usually respond within 24 hours.", sw: "Kwa kawaida tunajibu ndani ya saa 24." },
  "contact.map.view": { en: "View location on Mapcarta", sw: "Angalia eneo kwenye Mapcarta" },

  // Subjects
  "subject.sciences": { en: "Sciences", sw: "Sayansi" },
  "subject.sciences.desc": { en: "Physics, Chemistry, Biology, and Agriculture.", sw: "Fizikia, Kemia, Baiolojia, na Kilimo." },
  "subject.maths": { en: "Mathematics", sw: "Hisabati" },
  "subject.maths.desc": { en: "Pure Maths, Statistics, and Financial calculation.", sw: "Hisabati Pure, Takwimu, na Hesabu za Fedha." },
  "subject.languages": { en: "Languages", sw: "Lugha" },
  "subject.languages.desc": { en: "English, Swahili, and Foreign language options.", sw: "Kiingereza, Kiswahili, na Chaguzi za Lugha za Kigeni." },
  "subject.arts": { en: "Arts & Humanities", sw: "Sanaa na Ubinadamu" },
  "subject.arts.desc": { en: "History, Geography, and Fine Art.", sw: "Historia, Jiografia, na Sanaa." },
  "subject.social": { en: "Social Sciences", sw: "Sayansi ya Jamii" },
  "subject.social.desc": { en: "Economics, Commerce, and Religious Studies.", sw: "Uchumi, Biashara, na Masomo ya Dini." },
  "subject.ict": { en: "ICT & Coding", sw: "TEHAMA na Usimbuaji" },
  "subject.ict.desc": { en: "Digital literacy and modern computing skills.", sw: "Ujuzi wa kidijitali na ujuzi wa kisasa wa kompyuta." },
  "subject.kiswahili": { en: "Kiswahili", sw: "Kiswahili" },
  "subject.vocational": { en: "Vocational Skills", sw: "Stadi za Kazi" },

  // Student Life
  "life.badge": { en: "Beyond the Classroom", sw: "Zaidi ya Darasa" },
  "life.title": { en: "Life at Sacred Heart.", sw: "Maisha katika Sacred Heart." },
  "life.desc": { en: "School is more than just books. It's where passions are discovered and lifelong friendships are made.", sw: "Shule ni zaidi ya vitabu tu. Ni mahali ambapo vipaji hugunduliwa na urafiki wa maisha yote huanzishwa." },

  // Video Tour
  "video.badge": { en: "The Experience", sw: "Uzoefu" },
  "video.title": { en: "Experience Our Legacy in Motion.", sw: "Pata Uzoefu wa Urithi Wetu kwa Vitendo." },
  "video.story": { en: "Sacred Heart: Our Story", sw: "Sacred Heart: Hadithi Yetu" },
  "video.subtitle": { en: "Official School Documentary \u2022 2026", sw: "Filamu Rasmi ya Shule \u2022 2026" },

  // CTA
  "cta.title": { en: "Ready to Shape Your Future?", sw: "Uko Tayari Kuunda Siku Zako Zijazo?" },
  "cta.desc": { en: "Join a community of scholars, innovators, and leaders. Applications for 2026 are open.", sw: "Jiunge na jumuiya ya wasomi, wavumbuzi, na viongozi. Maombi ya mwaka 2026 yamefunguliwa." },
  "cta.apply": { en: "Apply Now", sw: "Omba Sasa" },
  "cta.visit": { en: "Schedule a Visit", sw: "Panga Kutembelea" },
  "cta.start": { en: "Start Your Application", sw: "Anza Ombi Lako" },
  "cta.step": { en: "Take the first step towards excellence today.", sw: "Chukua hatua ya kwanza kuelekea ubora leo." },
  "cta.feature1": { en: "World-class facilities", sw: "Vifaa vya kiwango cha juu" },
  "cta.feature2": { en: "Expert faculty mentorship", sw: "Ushauri wa walimu wataalamu" },
  "cta.feature3": { en: "Holistic development programs", sw: "Mipango ya maendeleo ya jumla" },
  "admissions.hero.subtitle": { en: "Join Sacred Heart Secondary School and embark on a journey of academic excellence", sw: "Jiunge na Shule ya Sekondari ya Sacred Heart na uanze safari ya ubora wa kitaaluma" },
  "admissions.dates.title": { en: "2025 Admission Dates", sw: "Tarehe za Usajili 2025" },
  "admissions.dates.opens": { en: "Application Opens", sw: "Maombi Yanafunguliwa" },
  "admissions.dates.deadline": { en: "Application Deadline", sw: "Mwisho wa Maombi" },
  "admissions.dates.exam": { en: "Entrance Examination", sw: "Mtihani wa Kujiunga" },
  "admissions.process.title": { en: "Admission Process", sw: "Mchakato wa Usajili" },
  "admissions.process.subtitle": { en: "Follow these simple steps to apply for admission at Sacred Heart", sw: "Fuata hatua hizi rahisi kuomba usajili Sacred Heart" },
  "admissions.step1.title": { en: "Download Form", sw: "Pakua Fomu" },
  "admissions.step1.desc": { en: "Get the application form from our office or download online", sw: "Chukua fomu ya maombi ofisini kwetu au pakua mtandaoni" },
  "admissions.step2.title": { en: "Fill Application", sw: "Jaza Maombi" },
  "admissions.step2.desc": { en: "Complete all sections of the application form accurately", sw: "Jaza sehemu zote za fomu ya maombi kwa usahihi" },
  "admissions.step3.title": { en: "Submit Documents", sw: "Wasilisha Nyaraka" },
  "admissions.step3.desc": { en: "Submit form with all required documents to the school office", sw: "Wasilisha fomu pamoja na nyaraka zote zinazohitajika ofisini" },
  "admissions.step4.title": { en: "Entrance Exam", sw: "Mtihani wa Kujiunga" },
  "admissions.step4.desc": { en: "Attend the scheduled entrance examination", sw: "Hudhuria mtihani wa kujiunga uliopangwa" },
  "admissions.step5.title": { en: "Interview", sw: "Usaili" },
  "admissions.step5.desc": { en: "Attend interview with parents/guardians", sw: "Hudhuria usaili akiwa na wazazi/walezi" },
  "admissions.step6.title": { en: "Admission", sw: "Usajili" },
  "admissions.step6.desc": { en: "Receive admission letter and complete registration", sw: "Pokea barua ya usajili na ukamilishe usajili" },
  "admissions.requirements.title": { en: "Requirements", sw: "Mahitaji" },
  "admissions.requirements.subtitle": { en: "Documents needed for admission application", sw: "Nyaraka zinazohitajika kwa maombi ya usajili" },
  "admissions.req.psle": { en: "Completed Primary School Leaving Examination (PSLE) Certificate", sw: "Cheti cha Kumaliza Elimu ya Msingi (PSLE)" },
  "admissions.req.birth": { en: "Birth Certificate (certified copy)", sw: "Cheti cha Kuzaliwa (nakala iliyothibitishwa)" },
  "admissions.req.photo": { en: "Four recent passport-size photographs", sw: "Picha nne za hivi karibuni za ukubwa wa pasipoti" },
  "admissions.req.medical": { en: "Medical examination report from recognized hospital", sw: "Ripoti ya uchunguzi wa matibabu kutoka hospitali inayotambulika" },
  "admissions.req.reports": { en: "Previous school reports and certificates", sw: "Ripoti za shule zilizopita na vyeti" },
  "admissions.req.id": { en: "Parent/Guardian identification document", sw: "Kitambulisho cha Mzazi/Mlezi" },
  "admissions.fees.title": { en: "Fee Structure", sw: "Muundo wa Ada" },
  "admissions.fees.subtitle": { en: "2025 Academic Year Fee Schedule", sw: "Ratiba ya Ada ya Mwaka wa Masomo 2025" },
  "admissions.fee.tuition": { en: "Tuition Fee (per term)", sw: "Ada ya Shule (kwa muhula)" },
  "admissions.fee.boarding": { en: "Boarding Fee (per term)", sw: "Ada ya Bweni (kwa muhula)" },
  "admissions.fee.dev": { en: "Development Fund (annual)", sw: "Mfuko wa Maendeleo (kila mwaka)" },
  "admissions.fee.reg": { en: "Registration Fee (once)", sw: "Ada ya Usajili (mara moja)" },
  "admissions.fee.uniform": { en: "Uniform & Materials", sw: "Sare na Vifaa" },
  "admissions.download.title": { en: "Download Application Form", sw: "Pakua Fomu ya Maombi" },
  "admissions.download.desc": { en: "Get the official admission application form and fill it at your convenience.", sw: "Chukua fomu rasmi ya maombi ya usajili na uijaze kwa urahisi wako." },
  "admissions.download.button": { en: "Download Form (PDF)", sw: "Pakua Fomu (PDF)" },
  "admissions.help.title": { en: "Need Help?", sw: "Unahitaji Msaada?" },
  "admissions.help.desc": { en: "Contact our admissions office for any questions or assistance.", sw: "Wasiliana na ofisi yetu ya usajili kwa maswali yoyote au msaada." },

  // About Section
  "about.badge": { en: "About Sacred Heart", sw: "Kuhusu Sacred Heart" },
  "about.title1": { en: "Shaping Futures Since", sw: "Kuunda Siku Zijazo Tangu" },
  "about.description": {
    en: "Sacred Heart High School has been a beacon of educational excellence in our community for decades. We believe in holistic education that develops not just the mind, but also the character and spirit of every student.",
    sw: "Shule ya Sacred Heart imekuwa mwanga wa ubora wa elimu katika jamii yetu kwa miongo kadhaa. Tunaamini katika elimu ya jumla inayolea si akili tu, bali pia tabia na roho ya kila mwanafunzi."
  },
  "about.history.desc": {
    en: "Over the decades, we have grown from a small community school to one of the leading educational institutions in the region, consistently producing top performers in national examinations while maintaining our commitment to holistic education.",
    sw: "Katika miongo kadhaa, tumekua kutoka shule ndogo ya jamii hadi kuwa moja ya taasisi zinazoongoza za elimu katika mkoa, tukizalisha wahitimu bora mfululizo katika mitihani ya kitaifa huku tukidumisha kujitolea kwetu kwa elimu ya jumla."
  },
  "about.guardian.badge": { en: "Patronage", sw: "Udhamini" },
  "about.guardian.title": { en: "Our School Guardian", sw: "Mlezi wa Shule Wetu" },
  "about.guardian.desc1": {
    en: "We are guided by the spiritual and moral support of our dedicated guardian who ensures that the school maintains its core values and mission.",
    sw: "Tunaongozwa na msaada wa kiroho na kimaadili wa mlezi wetu aliyejitolea ambaye anahakikisha kuwa shule inadumisha maadili yake makuu na dhamira yake."
  },
  "about.guardian.desc2": {
    en: "Their unwavering commitment to the holistic development of our students provides a strong foundation for character building and academic success.",
    sw: "Kujitolea kwao kusikoayumba kwa maendeleo ya jumla ya wanafunzi wetu kunatoa msingi imara wa kujenga tabia na mafanikio ya kitaaluma."
  },
  "about.guardian.name": { en: "Rev. Father Guardian", sw: "Baba Paroko Mlezi" },
  "about.guardian.role": { en: "School Guardian / Patron", sw: "Mlezi wa Shule / Mdhamini" },
  "about.values.subtitle": {
    en: "Our core values guide everything we do at Sacred Heart Secondary School",
    sw: "Maadili yetu makuu yanaongoza kila kitu tunachofanya katika Shule ya Sekondari ya Sacred Heart"
  },
  "about.leadership.badge": { en: "Our Leadership", sw: "Uongozi Wetu" },
  "about.leadership.title": { en: "Meet Our Team", sw: "Kutana na Timu Yetu" },
  "about.leadership.subtitle": {
    en: "Dedicated professionals committed to educational excellence",
    sw: "Wataalamu waliojitolea kwa ubora wa elimu"
  },
  "about.cta.title": { en: "Ready to Join Our Community?", sw: "Uko Tayari Kujiunga na Jumuiya Yetu?" },
  "about.cta.desc": {
    en: "Take the first step towards excellence. Apply now and become part of the Sacred Heart family.",
    sw: "Chukua hatua ya kwanza kuelekea ubora. Omba sasa na uwe sehemu ya familia ya Sacred Heart."
  },
  "mission.hero.subtitle": { en: "Our commitment to educational excellence", sw: "Kujitolea kwetu kwa ubora wa elimu" },
  "mission.commitments.badge": { en: "Our Commitments", sw: "Ahadi Zetu" },
  "mission.commitments.title": { en: "How We Fulfill Our Mission", sw: "Jinsi Tunavyotimiza Dhima Yetu" },
  "mission.point1.title": { en: "Quality Education", sw: "Elimu Bora" },
  "mission.point1.desc": { en: "Providing comprehensive, world-class education that meets international standards while respecting local values.", sw: "Kutoa elimu ya kina, ya kiwango cha ulimwengu inayokidhi viwango vya kimataifa huku tukiheshimu maadili ya mahali husika." },
  "mission.point2.title": { en: "Holistic Development", sw: "Maendeleo ya Jumla" },
  "mission.point2.desc": { en: "Nurturing the whole person—intellectually, spiritually, physically, and emotionally.", sw: "Kumkuza mtu mzima—kiakili, kiroho, kimwili, na kihisia." },
  "mission.point3.title": { en: "Community Building", sw: "Ujenzi wa Jumuiya" },
  "mission.point3.desc": { en: "Creating a supportive environment where every student feels valued and empowered to succeed.", sw: "Kutengeneza mazingira ya kusaidiana ambapo kila mwanafunzi anajihisi mwenye thamani." },
  "mission.point4.title": { en: "Critical Thinking", sw: "Fikra Tunduizi" },
  "mission.point4.desc": { en: "Developing analytical minds capable of solving complex problems and making informed decisions.", sw: "Kuendeleza akili zenye uwezo wa kuchanganua na kutatua matatizo magumu." },
  "mission.point5.title": { en: "Moral Values", sw: "Maadili" },
  "mission.point5.desc": { en: "Instilling strong ethical principles that guide students throughout their lives.", sw: "Kujenga kanuni imara za kimaadili zinazowaongoza wanafunzi katika maisha yao yote." },
  "mission.point6.title": { en: "Excellence", sw: "Ubora" },
  "mission.point6.desc": { en: "Striving for the highest standards in all academic and extracurricular endeavors.", sw: "Kujitahidi kufikia viwango vya juu zaidi katika taaluma na shughuli za ziada." },
  "mission.practice.badge": { en: "Mission in Practice", sw: "Dhima Katika Vitendo" },
  "mission.practice.title": { en: "Every Day, Every Student", sw: "Kila Siku, Kila Mwanafunzi" },
  "mission.practice.desc": {
    en: "Our mission comes alive in our classrooms, laboratories, sports fields, and community service programs. We believe that education extends beyond textbooks and examinations.",
    sw: "Dhima yetu inakuwa hai katika madarasa yetu, maabara, viwanja vya michezo, na programu za huduma kwa jamii. Tunaamini kuwa elimu inaenda mbali zaidi ya vitabu na mitihani."
  },
  "mission.practice.item1.title": { en: "Morning Assembly", sw: "Mkutano wa Asubuhi" },
  "mission.practice.item1.desc": { en: "Starting each day with reflection and motivation", sw: "Kuanza kila siku kwa tafakari na motisha" },
  "mission.practice.item2.title": { en: "Interactive Learning", sw: "Kujifunza kwa Kushirikiana" },
  "mission.practice.item2.desc": { en: "Engaging lessons that inspire curiosity", sw: "Masomo yanayoshirikisha na kuchochea udadisi" },
  "mission.practice.item3.title": { en: "Mentorship Programs", sw: "Programu za Ushauri", },
  "mission.practice.item3.desc": { en: "Personal guidance for every student", sw: "Mwongozo wa kibinafsi kwa kila mwanafunzi" },
  "mission.practice.item4.title": { en: "Community Service", sw: "Huduma kwa Jamii" },
  "mission.practice.item4.desc": { en: "Giving back and building character", sw: "Kutoa msaada na kujenga tabia" },
  "about.legacy": { en: "Since 1985.", sw: "Tangu 1985." },
  "about.mission.title": { en: "Our Mission", sw: "Dhamira Yetu" },
  "about.mission.text": {
    en: "To provide quality education that nurtures the whole person—intellectually, spiritually, and socially—preparing students to become responsible citizens and leaders of tomorrow.",
    sw: "Kutoa elimu bora inayolea mtu mzima—kielimu, kiroho, na kijamii."
  },
  "about.vision.title": { en: "Our Vision", sw: "Maono Yetu" },
  "about.vision.text": {
    en: "To be a leading institution that empowers students to excel academically while embracing strong moral values.",
    sw: "Kuwa taasisi inayoongoza inayowawezesha wanafunzi kufaulu kielimu huku wakikumbatia maadili imara."
  },
  "vision.hero.subtitle": { en: "Our aspirations for the future of education", sw: "Matarajio yetu kwa ajili ya elimu ya baadaye" },
  "vision.pillars.badge": { en: "Vision Pillars", sw: "Nguzo za Maono" },
  "vision.pillars.title": { en: "Building Tomorrow's Leaders", sw: "Kujenga Viongozi wa Kesho" },
  "vision.point1.title": { en: "Global Competitiveness", sw: "Ushindani wa Kimataifa" },
  "vision.point1.desc": { en: "Preparing students to excel in an increasingly interconnected world with skills that transcend borders.", sw: "Kuwaandaa wanafunzi kufanya vizuri katika ulimwengu unaozidi kuunganishwa wenye ujuzi usio na mipaka." },
  "vision.point2.title": { en: "Innovation Leaders", sw: "Viongozi wa Uvumbuzi" },
  "vision.point2.desc": { en: "Fostering a culture of creativity and critical thinking that drives positive change in society.", sw: "Kukuza utamaduni wa ubunifu na fikra tunduizi unaochochea mabadiliko chanya katika jamii." },
  "vision.point3.title": { en: "Academic Excellence", sw: "Ubora wa Kitaaluma" },
  "vision.point3.desc": { en: "Maintaining the highest standards of academic achievement while nurturing individual potential.", sw: "Kudumisha viwango vya juu vya mafanikio ya kitaaluma huku tukikuza uwezo wa kila mmoja." },
  "vision.point4.title": { en: "Community Impact", sw: "Athari kwa Jamii" },
  "vision.point4.desc": { en: "Developing responsible citizens who contribute meaningfully to their communities and nation.", sw: "Kuwaendeleza raia wenye kuwajibika ambao wanachangia kikamilifu katika jamii zao na taifa." },
  "vision.action.badge": { en: "Vision in Action", sw: "Maono Katika Vitendo" },
  "vision.action.title": { en: "Turning Vision Into Reality", sw: "Kugeuza Maono Kuwa Ukweli" },
  "vision.action.desc": {
    en: "Our vision is not just words on paper—it's a living commitment that shapes every decision we make, every program we develop, and every student we nurture.",
    sw: "Maono yetu si maneno tu kwenye karatasi—ni ahadi hai inayounda kila uamuzi tunaofanya, kila programu tunayotengeneza, na kila mwanafunzi tunayemlea."
  },
  "vision.action.item1": { en: "Continuous curriculum innovation aligned with global standards", sw: "Uvumbuzi wa kila mara wa mtaala unaoendana na viwango vya kimataifa" },
  "vision.action.item2": { en: "Investment in cutting-edge facilities and technology", sw: "Uwekezaji katika vifaa na teknolojia ya hali ya juu" },
  "vision.action.item3": { en: "Strong partnerships with universities and industry leaders", sw: "Ushirikiano imara na vyuo vikuu na viongozi wa viwanda" },
  "vision.action.item4": { en: "Comprehensive student development programs", sw: "Programu pana za maendeleo ya wanafunzi" },
  "about.values.title": { en: "Our Values", sw: "Maadili Yetu" },
  "about.value1": { en: "Academic Excellence", sw: "Ubora wa Masomo" },
  "about.value2": { en: "Moral Integrity", sw: "Uadilifu wa Kimaadili" },
  "about.value3": { en: "Community Service", sw: "Huduma kwa Jamii" },
  "about.value4": { en: "Innovation & Creativity", sw: "Uvumbuzi na Ubunifu" },

  // Facilities Section
  "facilities.badge": { en: "World-Class Facilities", sw: "Vifaa vya Kiwango cha Juu" },
  "facilities.title1": { en: "Learning Spaces That", sw: "Sehemu za Kujifunza Zinazochochea" },
  "facilities.title2": { en: "Inspire", sw: "Msukumo" },
  "facilities.description": {
    en: "Our modern facilities are designed to provide students with the best environment for academic excellence and personal growth.",
    sw: "Vifaa vyetu vya kisasa vimeundwa kuwapa wanafunzi mazingira bora ya ubora wa masomo na ukuaji wa kibinafsi."
  },
  "facility.biologyLab": { en: "Science Labs", sw: "Maabara za Sayansi" },
  "facility.biologyLab.desc": { en: "Advanced laboratories equipped with modern apparatus for hands-on scientific discovery.", sw: "Maabara za juu zilizo na vifaa vya kisasa kwa ugunduzi wa kisayansi." },
  "facility.physicsLab": { en: "Boarding Facilities", sw: "Vifaa vya Bweni" },
  "facility.physicsLab.desc": { en: "Safe, comfortable, and well-managed dormitories that feel like a second home.", sw: "Mabweni salama, starehe na yaliyosimamiwa vizuri." },
  "facility.chemistryLab": { en: "Digital Classrooms", sw: "Madarasa ya Kidijitali" },
  "facility.chemistryLab.desc": { en: "Classrooms integrated with the latest learning technology for an interactive experience.", sw: "Madarasa yaliyounganishwa na teknolojia ya hivi karibuni." },
  "facility.computerLab": { en: "Computer Lab", sw: "Maabara ya Kompyuta" },
  "facility.computerLab.desc": { en: "Modern ICT center with high-speed internet and the latest computers for digital learning.", sw: "Kituo cha kisasa cha TEHAMA chenye intaneti ya kasi." },
  "facility.library": { en: "Extensive Library", sw: "Maktaba Kubwa" },
  "facility.library.desc": { en: "A quiet sanctuary for research and reading, housing thousands of books and digital resources.", sw: "Mahali palivu kwa utafiti na kusoma." },
  "facility.sportsComplex": { en: "Sports Grounds", sw: "Viwanja vya Michezo" },
  "facility.sportsComplex.desc": { en: "Excellent facilities for football, basketball, and track events to promote physical fitness.", sw: "Vifaa bora kwa mpira wa miguu, mpira wa kikapu, na riadha." },
  "facility.diningHall": { en: "Dining Hall", sw: "Bwalo la Chakula" },
  "facility.diningHall.desc": { en: "Spacious and hygienic dining environment focusing on nutrition and student wellbeing.", sw: "Mazingira mapana na ya usafi ya kulia yakilenga lishe." },
  "facility.explore": { en: "Explore Facility", sw: "Gundua Vifaa" },

  // News Section
  "news.badge": { en: "Latest Updates", sw: "Habari za Hivi Karibuni" },
  "news.title": { en: "News &", sw: "Habari na" },
  "news.title2": { en: "Events", sw: "Matukio" },
  "news.viewAll": { en: "View All News", sw: "Tazama Habari Zote" },
  "news.readMore": { en: "Read More", sw: "Soma Zaidi" },
  "news.item1.title": { en: "2025 Academic Year Admissions Now Open", sw: "Usajili wa Mwaka wa Masomo 2025 Sasa Umefunguliwa" },
  "news.item1.desc": { en: "We are excited to welcome the next generation of leaders.", sw: "Tunafurahi kukaribisha kizazi kijacho cha viongozi." },
  "news.item2.title": { en: "National Science Competition Winners", sw: "Washindi wa Mashindano ya Sayansi ya Kitaifa" },
  "news.item2.desc": { en: "First place in the National Secondary Schools Science Competition.", sw: "Nafasi ya kwanza katika Mashindano ya Sayansi ya Shule za Sekondari za Kitaifa." },
  "news.item3.title": { en: "Annual Sports Day Celebration", sw: "Sherehe za Siku ya Michezo ya Kila Mwaka" },
  "news.item3.desc": { en: "Join us for the annual inter-house sports competition.", sw: "Jiunge nasi kwa mashindano ya michezo ya kila mwaka kati ya nyumba." },
  "news.item4.title": { en: "New Computer Lab Inauguration", sw: "Uzinduzi wa Maabara Mpya ya Kompyuta" },
  "news.item4.desc": { en: "50 new workstations added to our ICT department.", sw: "Vituo vipya 50 vya kazi vimeongezwa kwenye idara yetu ya TEHAMA." },
  "news.category.announcement": { en: "Announcement", sw: "Tangazo" },
  "news.category.achievement": { en: "Achievement", sw: "Mafanikio" },
  "news.category.event": { en: "Event", sw: "Tukio" },
  "news.category.news": { en: "News", sw: "Habari" },

  // Testimonials
  "test.title": { en: "Voices of our Community.", sw: "Sauti za Jumuiya Yetu." },
  "test.desc": { en: "Hear from parents, students, and alumni about their Sacred Heart experience.", sw: "Sikia kutoka kwa wazazi, wanafunzi, na wahitimu juu ya uzoefu wao wa Sacred Heart." },
  "test.role1": { en: "Parent, Class of 2024", sw: "Mzazi, Darasa la 2024" },
  "test.content1": { en: "Sacred Heart has been transformative for my child's academic performance.", sw: "Sacred Heart imekuwa mabadiliko makubwa kwa kilele cha masomo ya mwanangu." },
  "test.role2": { en: "Head Prefect, Class of 2025", sw: "Kaka Mkuu, Darasa la 2025" },
  "test.role3": { en: "Sacred Heart Alumni", sw: "Mhitimu wa Sacred Heart" },
  "test.content2": { en: "Being part of this school has opened so many doors for me.", sw: "Kuwa sehemu ya shule hii kumenifungulia milango mingi sana." },
  "test.content3": { en: "The teachers here truly care about our growth.", sw: "Walimu hapa wanajali sana ukuaji wetu." },
  "test.content4": { en: "The best choice for holistic education.", sw: "Chaguo bora kwa elimu ya jumla." },

  // Footer
  "footer.tagline": { en: "Nurturing minds, inspiring hearts, and shaping futures since 1985. Education is the way up.", sw: "Kulea akili, kuchochea mioyo, na kuunda siku zijazo tangu 1985. Elimu ndiyo njia juu." },
  "footer.quickLinks": { en: "Quick Links", sw: "Viungo vya Haraka" },
  "footer.portals": { en: "Portals", sw: "Lango" },
  "footer.contactUs": { en: "Contact Us", sw: "Wasiliana Nasi" },
  "footer.privacyPolicy": { en: "Privacy Policy", sw: "Sera ya Faragha" },
  "footer.termsOfService": { en: "Terms of Service", sw: "Masharti ya Huduma" },
  "footer.rights": { en: "All rights reserved.", sw: "Haki zote zimehifadhiwa." },
  "footer.address": { en: "Sacred Heart Secondary School, Mbezi Beach, Dar es Salaam", sw: "Shule ya Sekondari ya Sacred Heart, Mbezi Beach, Dar es Salaam" },
  "footer.phone": { en: "+255 754 555 666", sw: "+255 754 555 666" },
  "footer.email": { en: "info@sacredheart.ac.tz", sw: "info@sacredheart.ac.tz" },
  "footer.newsletter": { en: "Newsletter", sw: "Jarida" },
  "footer.newsletterDesc": { en: "Subscribe to get the latest updates and news.", sw: "Jiunge ili kupata habari na sasisho za hivi karibuni." },
  "footer.subscribe": { en: "Subscribe", sw: "Jiunge" },

  // Auth
  "auth.login": { en: "Login", sw: "Ingia" },
  "auth.signup": { en: "Sign Up", sw: "Jisajili" },
  "auth.logout": { en: "Logout", sw: "Ondoka" },
  "auth.email": { en: "Email", sw: "Barua Pepe" },
  "auth.password": { en: "Password", sw: "Nenosiri" },
  "auth.fullName": { en: "Full Name", sw: "Jina Kamili" },
  "auth.selectRole": { en: "Select Role", sw: "Chagua Jukumu" },
  "auth.welcomeBack": { en: "Welcome Back", sw: "Karibu Tena" },
  "auth.createAccount": { en: "Create Account", sw: "Fungua Akaunti" },
  "auth.noAccount": { en: "Don't have an account?", sw: "Huna akaunti?" },
  "auth.hasAccount": { en: "Already have an account?", sw: "Una akaunti tayari?" },
  "auth.signupSubtitle": { en: "Join our school community", sw: "Jiunge na jamii yetu ya shule" },

  // FAQ Section
  "faq.title": { en: "Frequently Asked Questions", sw: "Maswali Yanayoulizwa Sana" },
  "faq.desc": { en: "Find answers to common questions about admissions, academics, and student life.", sw: "Pata majibu ya maswali ya kawaida kuhusu usajili, taaluma, na maisha ya mwanafunzi." },
  "faq.q1": { en: "When do admissions open?", sw: "Usajili unafunguliwa lini?" },
  "faq.a1": { en: "Admissions typically open in September for the following academic year.", sw: "Usajili kawaida hufunguliwa Septemba kwa mwaka wa masomo unaofuata." },
  "faq.q2": { en: "Does the school offer boarding?", sw: "Je, shule inatoa huduma ya bweni?" },
  "faq.a2": { en: "Yes, Sacred Heart provides modern, secure boarding facilities for both boys and girls.", sw: "Ndiyo, Sacred Heart inatoa vifaa vya kisasa na salama vya bweni kwa wavulana na wasichana." },
  "faq.q3": { en: "What extracurriculars are available?", sw: "Je, kuna shughuli gani za ziada?" },
  "faq.a3": { en: "We offer sports, clubs (Science, Debate, Drama), and music programs.", sw: "Tunatoa michezo, klabu (Sayansi, Mdahalo, Tamthilia), na programu za muziki." },
  "faq.q4": { en: "Is there school transport?", sw: "Je, kuna usafiri wa shule?" },
  "faq.a4": { en: "Yes, we have a fleet of school buses covering major routes in the city.", sw: "Ndiyo, tuna mabasi ya shule yanayochukua njia kuu jijini." },
  "faq.q5": { en: "How can I track performance?", sw: "Ninawezaje kufuatilia maendeleo ya mwanangu?" },
  "faq.a5": { en: "Parents receive regular reports and can access the Parent Portal for real-time updates.", sw: "Wazazi hupokea ripoti za mara kwa mara na wanaweza kufikia Lango la Mzazi kwa sasisho za wakati halisi." },

  // New Pages Content
  "nursery.hero.subtitle": { en: "Nursery Section: The first step in your child's journey to excellence", sw: "Sehemu ya Chekechea: Hatua ya kwanza katika safari ya mtoto wako kuelekea ubora" },
  "nursery.title": { en: "A Home Away From Home", sw: "Nyumbani Mbali na Nyumbani" },
  "nursery.subtitle": { en: "Siima Nursery focuses on the holistic development of our youngest learners.", sw: "Chekechea ya Siima inazingatia maendeleo ya jumla ya wanafunzi wetu wadogo." },
  "nursery.desc": { en: "Our Nursery school provides a safe, vibrant, and stimulating environment where children learn through discovery and play.", sw: "Shule yetu ya Chekechea inatoa mazingira salama, mahiri, na yenye kusisimua ambapo watoto hujifunza kupitia uvumbuzi na michezo." },
  "nursery.class.baby": { en: "Baby Class", sw: "Darasa la Watoto" },
  "nursery.class.baby.desc": { en: "Ages 3-4: Focusing on socialization, speech development, and play-based learning.", sw: "Umri wa miaka 3-4: Lengo ni kushirikiana na wengine, maendeleo ya hotuba, na kujifunza kwa michezo." },
  "nursery.class.middle": { en: "Middle Class", sw: "Darasa la Kati" },
  "nursery.class.middle.desc": { en: "Ages 4-5: Introduction to basic literacy, numeracy, and creative arts.", sw: "Umri wa miaka 4-5: Utangulizi wa kusoma, kuhesabu, na sanaa za ubunifu." },
  "nursery.class.preunit": { en: "Pre-Unit", sw: "Darasa la Maandalizi" },
  "nursery.class.preunit.desc": { en: "Ages 5-6: Transition year preparing children for Standard 1 with foundational skills.", sw: "Umri wa miaka 5-6: Mwaka wa mpito unaowaandaa watoto kwa Darasa la 1." },
  "nursery.goals.title": { en: "Learning Goals", sw: "Malengo ya Kujifunza" },
  "nursery.join.title": { en: "Join the Siima Family", sw: "Jiunge na Familia ya Siima" },
  "nursery.join.desc": { en: "Enroll your child today and give them the best foundation for their academic future.", sw: "Msajili mtoto wako leo na mpe msingi bora wa maisha yake ya baadaye ya kitaaluma." },
  "nursery.hero.badge": { en: "Nurturing Young Minds", sw: "Kulea Akili za Kichanga" },
  "nursery.goal1": { en: "Communication and Language development", sw: "Maendeleo ya Mawasiliano na Lugha" },
  "nursery.goal2": { en: "Physical and Motor skills development", sw: "Maendeleo ya Stadi za Mwili na Misuli" },
  "nursery.goal3": { en: "Personal, Social, and Emotional awareness", sw: "Ufahamu wa Binafsi, Jamii, na Kihisia" },
  "nursery.goal4": { en: "Early Mathematics and Problem-solving", sw: "Hisabati za Awali na Kutatua Matatizo" },
  "nursery.goal5": { en: "Expressive Arts and Design", sw: "Sanaa za Maonyesho na Ubunifu" },
  "nursery.activity.arts": { en: "Arts & Crafts", sw: "Sanaa na Ufundi" },
  "nursery.activity.music": { en: "Music & Rhymes", sw: "Muziki na Mashairi" },
  "nursery.activity.social": { en: "Social Play", sw: "Michezo ya Kijamii" },
  "nursery.activity.values": { en: "Moral Values", sw: "Maadili ya Maisha" },

  "primary.hero.badge": { en: "Excellence in Foundations", sw: "Ubora katika Msingi" },
  "primary.desc.full": {
    en: "Founded on the principles of integrity and hard work, Siima Primary provides a comprehensive learning experience that prepares students for the challenges of modern secondary education and beyond.",
    sw: "Ikiongozwa na misingi ya uadilifu na kazi ngumu, Shule ya Msingi Siima hutoa uzoefu wa kina wa kujifunza unaowaandaa wanafunzi kwa changamoto za elimu ya sekondari ya kisasa na zaidi."
  },
  "primary.curr.item1": { en: "Intensive Literacy and Numeracy programs", sw: "Programu Madhubuti za Kusoma na Kuhesabu" },
  "primary.curr.item2": { en: "Standard 4 (SFNA) National Examination prep", sw: "Maandalizi ya Mtihani wa Kitaifa wa Darasa la 4 (SFNA)" },
  "primary.curr.item3": { en: "Standard 7 (PSLE) National Examination excellence", sw: "Ubora katika Mtihani wa Kitaifa wa Darasa la 7 (PSLE)" },
  "primary.curr.item4": { en: "ICT Integration in Classrooms", sw: "Ujumuishaji wa TEHAMA Madarasani" },
  "primary.curr.item5": { en: "Continuous monthly assessments", sw: "Tathmini Endelevu za Kila Mwezi" },
  "primary.achievements.title": { en: "Achievements & Recognition", sw: "Mafanikio na Kutambuliwa" },
  "primary.achievements.subtitle": { en: "Setting the bar high for primary education", sw: "Kuweka kiwango cha juu cha elimu ya msingi" },
  "primary.stats.digital": { en: "Digital Labs", sw: "Maabara za Kidijitali" },
  "primary.stats.digital.value": { en: "Available", sw: "Ipo" },
  "primary.facilities.desc": {
    en: "We believe that the environment is \"the third teacher\". Our campus is designed to be safe, interactive, and inspiring for children to explore their boundaries and learn through experience.",
    sw: "Tunaamini kuwa mazingira ni \"mwalimu wa tatu\". Kampasi yetu imeundwa kuwa salama, shirikishi, na yenye kutia moyo kwa watoto kuchunguza mipaka yao na kujifunza kupitia uzoefu."
  },
  "primary.facility.tag1": { en: "Modern Library", sw: "Maktaba ya Kisasa" },
  "primary.facility.tag2": { en: "Science Lab", sw: "Maabara ya Sayansi" },
  "primary.facility.tag3": { en: "Playground", sw: "Uwanja wa Michezo" },
  "primary.facility.tag4": { en: "Computer Hub", sw: "Kituo cha Kompyuta" },
  "primary.admissions.desc": {
    en: "Join one of the top-performing primary schools in the region. Enrollment is open for all standards at the beginning of the academic year.",
    sw: "Jiunge na moja ya shule za msingi zinazofanya vizuri zaidi mkoani. Udahili uko wazi kwa madarasa yote mwanzoni mwa mwaka wa masomo."
  },

  "primary.hero.subtitle": { en: "Standard 1 – Standard 7: Building a rock-solid foundation for future leaders", sw: "Darasa la 1 – Darasa la 7: Kujenga msingi imara kwa viongozi wa kesho" },
  "primary.title": { en: "A Tradition of Quality Education", sw: "Mapokeo ya Elimu Bora" },
  "primary.subtitle": { en: "Siima Primary School is dedicated to nurturing academic brilliance and moral uprightness.", sw: "Shule ya Msingi ya Siima imejitolea kulea udadi wa kitaaluma na uadilifu wa maadili." },
  "primary.curriculum.title": { en: "Our Curriculum", sw: "Mtaala Wetu" },
  "primary.curriculum.desc": { en: "We follow the Tanzania Institute of Education (TIE) curriculum, blended with modern teaching aids.", sw: "Tunafuata mtaala wa Taasisi ya Elimu Tanzania (TET), ukiambatana na vifaa vya kisasa vya kufundishia." },
  "primary.subjects.title": { en: "Key Subjects", sw: "Masomo Muhimu" },
  "primary.stats.passrate": { en: "National Pass Rate", sw: "Kiwango cha Kufaulu Kitaifa" },
  "primary.stats.staff": { en: "Qualified Staff", sw: "Wafanyakazi Waliohitimu" },
  "primary.stats.experience": { en: "Years Experience", sw: "Miaka ya Uzoefu" },
  "primary.facilities.title": { en: "Environment & Facilities", sw: "Mazingira na Vifaa" },

  "secondary.hero.subtitle": { en: "Form 1 – Form 4: Empowering students through a holistic curriculum", sw: "Kidato cha 1 – Kidato cha 4: Kuwawezesha wanafunzi kupitia mtaala wa jumla" },
  "secondary.structure.title": { en: "Academic Structure", sw: "Mfumo wa Kitaaluma" },
  "secondary.structure.desc": { en: "Our secondary education is structured into two main cycles focusing on core and choice subjects.", sw: "Elimu yetu ya sekondari imegawanywa katika mizunguko miwili mikuu ikilenga masomo ya msingi na ya hiyari." },
  "secondary.exams.title": { en: "Examination System", sw: "Mfumo wa Mitihani" },
  "secondary.exams.desc": { en: "Continuous assessment combined with national examinations to ensure academic excellence.", sw: "Tathmini inayoendelea ikijumuishwa na mitihani ya kitaifa ili kuhakikisha ubora wa kitaaluma." },
  "secondary.form1": { en: "Form 1", sw: "Kidato cha 1" },
  "secondary.form1.desc": { en: "Foundation year focusing on core subjects and transitioning to secondary education standards.", sw: "Mwaka wa msingi unaolenga masomo makuu na mpito kwenda kwenye viwango vya elimu ya sekondari." },
  "secondary.form2": { en: "Form 2", sw: "Kidato cha 2" },
  "secondary.form2.desc": { en: "Consolidation of knowledge with preparation for the National Form Two Assessment (FTNA).", sw: "Kuimarisha maarifa na maandalizi ya Tathmini ya Kitaifa ya Kidato cha Pili (FTNA)." },
  "secondary.form3": { en: "Form 3", sw: "Kidato cha 3" },
  "secondary.form3.desc": { en: "Specialization begins as students choose between science and arts/commercial streams.", sw: "Utaalamu huanza wanafunzi wanapochagua kati ya mikondo ya sayansi na sanaa/biashara." },
  "secondary.form4": { en: "Form 4", sw: "Kidato cha 4" },
  "secondary.form4.desc": { en: "Final year of O-Level focusing on intensive revision for the National Examination (CSEE).", sw: "Mwaka wa mwisho wa O-Level ukilenga marudio ya kina kwa ajili ya Mtihani wa Kitaifa (CSEE)." },
  "secondary.facility.studyRooms": { en: "Study Rooms", sw: "Vyumba vya Kujisomea" },
  "secondary.facility.studyRooms.desc": { en: "Quiet spaces designed for individual and group study sessions.", sw: "Sehemu tulivu zilizoundwa kwa ajili ya vipindi vya kujisomea binafsi na vya kikundi." },
  "secondary.academicExcellence": { en: "Academic Excellence", sw: "Ubora wa Kitaaluma" },
  "secondary.approach.title": { en: "Our Mission and Approach", sw: "Dhamira na Mtazamo Wetu" },
  "secondary.approach.desc": {
    en: "At Sacred Heart Secondary School, our academic mission is to provide an environment that nurtures intellectual curiosity, critical thinking, and a lifelong love for learning. Our teaching approach combines traditional academic rigor with modern innovative pedagogy, ensuring every student reaches their full potential.",
    sw: "Katika Shule ya Sekondari ya Sacred Heart, dhamira yetu ya kitaaluma ni kutoa mazingira yanayolea udadisi wa kiakili, kufikiri kwa kina, na upendo wa maisha kwa ajili ya kujifunza. Mtazamo wetu wa kufundisha unachanganya ukali wa kijadi wa kitaaluma na ufundishaji wa kisasa wa kibunifu, kuhakikisha kila mwanafunzi anafikia uwezo wake kamili."
  },
  "secondary.approach.item1": { en: "Standard-aligned learning objectives", sw: "Malengo ya kujifunza yanayozingatia viwango" },
  "secondary.approach.item2": { en: "Continuous assessment & feedback", sw: "Tathmini endelevu na maoni" },
  "secondary.approach.item3": { en: "Practical-oriented science education", sw: "Elimu ya sayansi inayolenga vitendo" },
  "secondary.approach.item4": { en: "ICT integration in all subjects", sw: "Ujumuishaji wa TEHAMA katika masomo yote" },
  "secondary.recognition.title": { en: "National Recognition", sw: "Utambuzi wa Kitaifa" },
  "secondary.recognition.quote": {
    en: "Our students consistently rank among the top performers in regional and national assessments, reflecting the strength of our academic framework.",
    sw: "Wanafunzi wetu mfululizo hushika nafasi kati ya wafanya vizuri zaidi katika tathmini za kikanda na kitaifa, ikionyesha nguvu ya mfumo wetu wa kitaaluma."
  },
  "secondary.subjects.subtitle": { en: "Comprehensive secondary education across all streams", sw: "Elimu ya sekondari ya kina katika mikondo yote" },
  "secondary.coreSubjects": { en: "Core Subjects", sw: "Masomo ya Lazima" },
  "secondary.optionalSubjects": { en: "Optional Subjects", sw: "Masomo ya Hiyari" },
  "secondary.exam.monthly": { en: "Monthly Tests", sw: "Mitihani ya Kila Mwezi" },
  "secondary.exam.monthly.desc": { en: "Internal assessments at the end of every month.", sw: "Tathmini za ndani mwishoni mwa kila mwezi." },
  "secondary.exam.midterm": { en: "Midterm Exams", sw: "Mitihani ya Katikati ya Muhula" },
  "secondary.exam.midterm.desc": { en: "Comprehensive testing in the middle of each term.", sw: "Mitihani ya kina katikati ya kila muhula." },
  "secondary.exam.annual": { en: "Annual Exams", sw: "Mitihani ya Mwaka" },
  "secondary.exam.annual.desc": { en: "Final year-end evaluations for promotion.", sw: "Tathmini za mwisho wa mwaka kwa ajili ya kupandishwa darasa." },
  "secondary.exam.national": { en: "National Exams (NECTA)", sw: "Mitihani ya Kitaifa (NECTA)" },
  "secondary.exam.national.desc": { en: "National Form 2 (FTNA) and Form 4 (CSEE) examinations.", sw: "Mitihani ya Kitaifa ya Kidato cha 2 (FTNA) na Kidato cha 4 (CSEE)." },
  "secondary.calendar.title": { en: "Academic Calendar", sw: "Kalenda ya Kitaaluma" },
  "secondary.calendar.desc": {
    en: "Stay updated with our school opening dates, term breaks, and examination periods. Our academic year typically begins in January and concludes in December.",
    sw: "Pata taarifa za tarehe za kufungua shule, mapumziko ya muhula, na vipindi vya mitihani. Mwaka wetu wa masomo kawaida huanza Januari na kuhitimishwa Desemba."
  },
  "secondary.nextTerm": { en: "Next Term", sw: "Muhula Ujao" },
  "secondary.classHours": { en: "Class Hours", sw: "Muda wa Masomo" },
  "secondary.facilities.subtitle": { en: "Environment designed for superior learning", sw: "Mazingira yaliyoundwa kwa ajili ya kujifunza kwa hali ya juu" },
  "secondary.achievements.title": { en: "Academic Achievements", sw: "Mafanikio ya Kitaaluma" },
  "secondary.achievements.item1": { en: "Ranked in top 10 regional schools for 3 consecutive years", sw: "Imeorodheshwa katika shule 10 bora za mkoa kwa miaka 3 mfululizo" },
  "secondary.achievements.item2": { en: "100% pass rate in the 2024 CSEE National Examinations", sw: "Kiwango cha kufaulu cha 100% katika Mitihani ya Kitaifa ya CSEE 2024" },
  "secondary.achievements.item3": { en: "Winners of the National Science Competition 2023", sw: "Washindi wa Mashindano ya Sayansi ya Kitaifa 2023" },
  "secondary.achievements.item4": { en: "Best Performing Students in Mathematics Category (Regional)", sw: "Wanafunzi Wanaofanya Vizuri Zaidi katika Kitengo cha Hisabati (Mkoa)" },
  "secondary.staff.desc": {
    en: "Our faculty consists of over 40 highly qualified and dedicated educators across various departments including Sciences, Humanities, Languages, and Vocational studies.",
    sw: "Kitivo chetu kinajumuisha zaidi ya waelimishaji 40 waliohitimu sana na waliojitolea katika idara mbalimbali ikiwemo Sayansi, Masomo ya Jamii, Lugha, na stadi za kazi."
  },
  "secondary.staff.view": { en: "View Teacher Profiles", sw: "Tazama Maelezo ya Walimu" },
  "secondary.civics": { en: "Civics", sw: "Uraia" },
  "secondary.commerce": { en: "Commerce", sw: "Biashara" },
  "secondary.bookkeeping": { en: "Bookkeeping", sw: "Uwekaji Hesabu" },
  "secondary.computerStudies": { en: "Computer Studies", sw: "Masomo ya Kompyuta" },
  "secondary.agriculture": { en: "Agriculture", sw: "Kilimo" },
  "secondary.technical": { en: "Technical subjects", sw: "Masomo ya Ufundi" },

  // Results Page
  "results.hero.title": { en: "Examination Results", sw: "Matokeo ya Mitihani" },
  "results.hero.subtitle": { en: "Access national examination results for Sacred Heart Secondary School students (S4567).", sw: "Pata matokeo ya mitihani ya kitaifa kwa wanafunzi wa Shule ya Sekondari ya Sacred Heart (S4567)." },
  "results.search.placeholder": { en: "Search for a year...", sw: "Tafuta mwaka..." },
  "results.view.external": { en: "View Results", sw: "Tazama Matokeo" },
  "results.necta.official": { en: "Official NECTA Results", sw: "Matokeo Rasmi ya NECTA" },
  "results.year.label": { en: "Year", sw: "Mwaka" },
  "results.form4.csee": { en: "CSEE (Form Four)", sw: "CSEE (Kidato cha Nne)" },
  "results.disclaimer": { en: "Note: You will be redirected to the official examination results website.", sw: "Maelezo: Utaelekezwa kwenye tovuti rasmi ya matokeo ya mitihani." },

  "life.clubs.title": { en: "Clubs & Societies", sw: "Klabu na Vyama" },
  "life.sports.title": { en: "Sports & Games", sw: "Michezo na Michezo" },
  "life.leadership.title": { en: "Student Leadership", sw: "Uongozi wa Wanafunzi" },
  "life.events.title": { en: "School Events", sw: "Matukio ya Shule" },

  // Student Life Page
  "life.hero.title": { en: "Student Life", sw: "Maisha ya Mwanafunzi" },
  "life.hero.subtitle": { en: "Growth beyond academics: Developing character, talent, and leadership", sw: "Ukuaji zaidi ya masomo: Kukuza tabia, talanta, na uongozi" },
  "life.intro.title": { en: "A Vibrant Community", sw: "Jumuiya Changamfu" },
  "life.intro.subtitle": { en: "Holistic Student Development", sw: "Maendeleo ya Jumla ya Mwanafunzi" },
  "life.intro.desc": { en: "Our school supports student development far beyond the classroom. We believe that extracurricular activities, leadership roles, and community service are essential for building confidence, teamwork, and a sense of responsibility in our students.", sw: "Shule yetu inasaidia maendeleo ya mwanafunzi mbali zaidi ya darasani. Tunaamini kuwa shughuli za ziada, majukumu ya uongozi, na huduma kwa jamii ni muhimu kwa kujenga kujiamini, kufanya kazi kwa pamoja, na hisia ya uwajibikaji kwa wanafunzi wetu." },
  "life.clubs.subtitle": { en: "Pursue your passions", sw: "Fuata mapenzi yako" },
  "life.club.debate": { en: "Debate Club", sw: "Klabu ya Mdahalo" },
  "life.club.debate.desc": { en: "Enhancing public speaking and critical thinking skills.", sw: "Kuimarisha stadi za kuzungumza mbele ya watu na kufikiri kwa kina." },
  "life.club.science": { en: "Science Club", sw: "Klabu ya Sayansi" },
  "life.club.science.desc": { en: "Exploring scientific phenomena through experiments.", sw: "Kuchunguza matukio ya kisayansi kupitia majaribio." },
  "life.club.ict": { en: "ICT/Computer Club", sw: "Klabu ya TEHAMA" },
  "life.club.ict.desc": { en: "Coding, digital design, and hardware exploration.", sw: "Kukodi, usanifu wa kidijitali, na uchunguzi wa vifaa." },
  "life.club.environment": { en: "Environment Club", sw: "Klabu ya Mazingira" },
  "life.club.environment.desc": { en: "Promoting sustainability and school campus greening.", sw: "Kukuza uendelevu na upandaji miti katika kampasi ya shule." },
  "life.club.music": { en: "Music & Drama Club", sw: "Klabu ya Muziki na Drama" },
  "life.club.music.desc": { en: "Showcasing talent through performances and productions.", sw: "Kuonyesha talanta kupitia maonyesho na uzalishaji." },
  "life.sport.football": { en: "Football", sw: "Mpira wa Miguu" },
  "life.sport.netball": { en: "Netball", sw: "Mpira wa Pete" },
  "life.sport.volleyball": { en: "Volleyball", sw: "Mpira wa Wavu" },
  "life.sport.athletics": { en: "Athletics", sw: "Riadha" },
  "life.sport.basketball": { en: "Basketball", sw: "Mpira wa Kikapu" },
  "life.sports.desc": { en: "Physical fitness and teamwork are central to life at Sacred Heart. Our sports program provides opportunities for both casual play and competitive representation in inter-school tournaments.", sw: "Usawa wa mwili na kazi ya pamoja ni muhimu kwa maisha ya Sacred Heart. Programu yetu ya michezo inatoa fursa kwa michezo ya kawaida na uwakilishi wa ushindani katika mashindano ya shule." },
  "life.champions.title": { en: "Regional Champions", sw: "Mabingwa wa Mkoa" },
  "life.champions.desc": { en: "Our Netball and Football teams are the current regional title holders, showcasing the spirit of excellence we foster on the field.", sw: "Timu zetu za Netiboli na Mpira wa Miguu ndizo washikiliaji wa sasa wa taji la mkoa, zikionyesha roho ya ubora tunayokuza uwanjani." },
  "life.leadership.head": { en: "Head Boy / Head Girl", sw: "Kaka Mkuu / Dada Mkuu" },
  "life.leadership.head.role": { en: "Representing the student body at the highest level.", sw: "Kuwakilisha jumuiya ya wanafunzi katika ngazi ya juu." },
  "life.leadership.prefects": { en: "Prefects", sw: "Viranja" },
  "life.leadership.prefects.role": { en: "Assisting in maintaining order and school discipline.", sw: "Saidia katika kudumisha utulivu na nidhamu ya shule." },
  "life.leadership.council": { en: "Student Councils", sw: "Mabaraza ya Wanafunzi" },
  "life.leadership.council.role": { en: "A platform for student voices in school decision-making.", sw: "Jukwaa la sauti za wanafunzi katika kufanya maamuzi ya shule." },
  "life.events.subtitle": { en: "Highlights of the academic year", sw: "Muhtasari wa mwaka wa masomo" },
  "life.event.sports": { en: "Sports Day", sw: "Siku ya Michezo" },
  "life.event.sports.desc": { en: "Annual inter-house athletic competitions.", sw: "Mashindano ya riadha ya kila mwaka kati ya nyumba." },
  "life.event.cultural": { en: "Cultural Day", sw: "Siku ya Utamaduni" },
  "life.event.cultural.desc": { en: "Celebrating our diverse Tanzanian heritage.", sw: "Kusherehekea urithi wetu tofauti wa Kitanzania." },
  "life.event.academic": { en: "Academic Competitions", sw: "Mashindano ya Kitaaluma" },
  "life.event.academic.desc": { en: "Inter-school quiz and debate finals.", sw: "Fainali za maswali na midahalo kati ya shule." },
  "life.event.graduation": { en: "Graduation Ceremony", sw: "Sherehe za Mahafali" },
  "life.event.graduation.desc": { en: "Celebrating the achievements of our Form 4 graduates.", sw: "Kusherehekea mafanikio ya wahitimu wetu wa Kidato cha 4." },
  "life.guidance.title": { en: "Guidance & Counseling", sw: "Mwongozo na Ushauri" },
  "life.guidance.desc": { en: "We provide a robust support system for students' personal and academic growth. Our dedicated counselors are always available to offer guidance on career paths, emotional well-being, and social challenges.", sw: "Tunatoa mfumo madhubuti wa msaada kwa ukuaji wa kibinafsi na wa kitaaluma wa wanafunzi. Washauri wetu waliojitolea wanapatikana kila wakati kutoa mwongozo juu ya njia za kazi, ustawi wa kihisia, na changamoto za kijamii." },
  "life.community.title": { en: "Community Activities", sw: "Shughuli za Jamii" },
  "life.community.item1": { en: "Environmental cleaning within the local community.", sw: "Usafi wa mazingira ndani ya jamii ya mtaa." },
  "life.community.item2": { en: "Charity visits and support programs for those in need.", sw: "Ziara za hisani na programu za msaada kwa wenye uhitaji." },
  "life.community.item3": { en: "Educational trips to historical and scientific sites.", sw: "Safari za mafunzo kwenye maeneo ya kihistoria na kisayansi." },
  "life.rules.title": { en: "Rules & Discipline", sw: "Sheria na Nidhamu" },
  "life.rules.desc": { en: "Sacred Heart maintains a high standard of discipline based on mutual respect and responsibility. Our code of conduct is designed to ensure a safe and productive learning environment for everyone.", sw: "Sacred Heart inadumisha kiwango cha juu cha nidhamu kulingana na heshima na uwajibikaji. Kanuni zetu za maadili zimeundwa ili kuhakikisha mazingira salama na yenye tija ya kujifunza kwa kila mtu." },
  "life.rules.conduct": { en: "Code of Conduct", sw: "Kanuni za Maadili" },
  "life.rules.conduct.desc": { en: "Detailed guidelines on behavior, punctuality, and academic integrity.", sw: "Miongozo ya kina juu ya tabia, kuzingatia muda, na uadilifu wa masomo." },
  "life.rules.uniform": { en: "Uniform Guidelines", sw: "Miongozo ya Sare" },
  "life.rules.uniform.desc": { en: "Strict adherence to the school uniform policy is required at all times.", sw: "Kuzingatia kwa dhati sera ya sare ya shule kunahitajika wakati wote." },
  "life.portal.title": { en: "Access the Student Portal", sw: "Ingia kwenye Lango la Mwanafunzi" },
  "life.portal.desc": { en: "Manage your academic journey, view timetables, and stay connected with your teachers.", sw: "Simamia safari yako ya kitaaluma, tazama ratiba, na uendelee kuwasiliana na walimu wako." },
  "life.portal.button": { en: "Go to Portal", sw: "Nenda kwenye Lango" },
  "life.counseling.title": { en: "Guidance & Counseling", sw: "Mwongozo na Ushauri" },
  "life.activities.music": { en: "Music & Drama", sw: "Muziki na Maigizo" },
  "life.activities.music.desc": { en: "Expressing creativity through stage and sound.", sw: "Kuelezea ubunifu kupitia jukwaa na sauti." },
  "life.activities.sports": { en: "Sports Teams", sw: "Timu za Michezo" },
  "life.activities.sports.desc": { en: "Developing teamwork and physical excellence.", sw: "Kuendeleza kazi ya pamoja na ubora wa kimwili." },
  "life.activities.debate": { en: "Debate Society", sw: "Chama cha Mijadala" },
  "life.activities.debate.desc": { en: "Training the critical voices of tomorrow.", sw: "Kufundisha sauti muhimu za kesho." },
  "life.activities.media": { en: "Media Club", sw: "Klabu ya Habari" },
  "life.activities.media.desc": { en: "Capturing the school's story through our lens.", sw: "Kunasa hadithi ya shule kupitia lenzi yetu." },
  "life.activities.languages": { en: "Foreign Languages", sw: "Lugha za Kigeni" },
  "life.activities.languages.desc": { en: "Connecting with the world through speech.", sw: "Kuunganisha na ulimwengu kupitia hotuba." },
  "life.activities.charity": { en: "Charity & Service", sw: "Sadaka na Huduma" },
  "life.activities.charity.desc": { en: "Building empathy through community impact.", sw: "Kujenga huruma kupitia athari za jamii." },

  "gallery.title": { en: "Capturing Our", sw: "Tukirekodi" },
  "gallery.legacy": { en: "Legacy.", sw: "Urithi Wetu." },
  "gallery.desc": { en: "A glimpse into the daily life and special moments at Sacred Heart.", sw: "Mtazamo wa maisha ya kila siku na matukio maalum huko Sacred Heart." },
  "gallery.viewFull": { en: "View Full size", sw: "Angalia Ukubwa Kamili" },
  "gallery.explore": { en: "Explore Full Gallery", sw: "Gundua Picha Zote" },

  "category.studentLife": { en: "Student Life", sw: "Maisha ya Mwanafunzi" },
  "category.academic": { en: "Academic Excellence", sw: "Ubora wa Kitaaluma" },
  "category.events": { en: "Events", sw: "Matukio" },
  "category.leadership": { en: "Student Leadership", sw: "Uongozi wa Wanafunzi" },
  "category.arts": { en: "Arts & Culture", sw: "Sanaa na Utamaduni" },
  "category.athletics": { en: "Athletics", sw: "Riadha" },

  "life.leadershipPerspective": { en: "Leadership Perspective", sw: "Mtazamo wa Uongozi" },
  "life.directorQuote": {
    en: "Education is not just about academic excellence, but about character formation. At Sacred Heart, we strive to mold the future leaders of our society by instilling discipline, integrity, and a thirst for knowledge.",
    sw: "Elimu si kuhusu ubora wa kitaaluma pekee, bali ni kuhusu kuunda tabia. Katika Sacred Heart, tunajitahidi kuwafinyanga viongozi wa baadaye wa jamii yetu kwa kupandikiza nidhamu, uadilifu, na kiu ya maarifa."
  },
  "life.directorDesc": {
    en: "We welcome you to be part of this transformative journey. Our gates are open to all who seek knowledge and wisdom in a serene and conducive environment.",
    sw: "Tunawakaribisha kuwa sehemu ya safari hii ya mabadiliko. Milango yetu iko wazi kwa wote wanaotafuta maarifa na hekima katika mazingira tulivu na wezeshi."
  },
  "life.directorRole": { en: "School Director", sw: "Mkurugenzi wa Shule" },

  "tags.ages35": { en: "Ages 3-5", sw: "Umri wa Miaka 3-5" },
  "tags.creativePlay": { en: "Creative Play", sw: "Michezo ya Ubunifu" },
  "tags.ages612": { en: "Ages 6-12", sw: "Umri wa Miaka 6-12" },
  "tags.foundation": { en: "Foundation", sw: "Msingi" },
  "tags.ages1317": { en: "Ages 13-17", sw: "Umri wa Miaka 13-17" },
  "tags.leadership": { en: "Leadership", sw: "Uongozi" },

  "common.apply": { en: "Apply Now", sw: "Omba Sasa" },
  "common.contact": { en: "Contact Us", sw: "Wasiliana Nasi" },
  "common.readMore": { en: "Read More", sw: "Soma Zaidi" },
  "common.back": { en: "Back", sw: "Rudi" },
  "common.viewAll": { en: "View All", sw: "Ona Yote" },
  "common.discover": { en: "Discover", sw: "Gundua" },
  "common.chatWhatsApp": { en: "Chat on WhatsApp", sw: "Chat kupitia WhatsApp" },
  "school.name": { en: "Sacred Heart Secondary School", sw: "Shule ya Sekondari Sacred Heart" },
  "school.siimaName": { en: "SIIMA Primary School", sw: "Shule ya Msingi ya SIIMA" },
  "school.name.short": { en: "Sacred Heart", sw: "Sacred Heart" },
  "school.type.secondary": { en: "Secondary School", sw: "Shule ya Sekondari" },

  // Contact Page
  "contact.page.hero.subtitle": { en: "Get in touch with Sacred Heart Secondary School. We'd love to hear from you!", sw: "Wasiliana na Shule ya Sekondari ya Sacred Heart. Tungependa kusikia kutoka kwako!" },
  "contact.page.sendMsg": { en: "Send us a Message", sw: "Tutumie Ujumbe" },
  "contact.page.info": { en: "Contact Information", sw: "Maelezo ya Mawasiliano" },
  "contact.form.fullname": { en: "Full Name", sw: "Jina Kamili" },
  "contact.form.name.placeholder": { en: "Your name", sw: "Jina lako" },
  "contact.form.phone.label": { en: "Phone", sw: "Simu" },
  "contact.form.subject.placeholder": { en: "Select a subject", sw: "Chagua mada" },
  "contact.form.admissions": { en: "Admissions Inquiry", sw: "Swali la Usajili" },
  "contact.form.academic": { en: "Academic Information", sw: "Taarifa za Kitaaluma" },
  "contact.form.fees": { en: "Fee Payment", sw: "Malipo ya Ada" },
  "contact.form.general": { en: "General Inquiry", sw: "Swali la Jumla" },
  "contact.form.other": { en: "Other", sw: "Nyingine" },
  "contact.form.msg.placeholder": { en: "How can we help you?", sw: "Tunaweza kukusaidia vipi?" },
  "contact.form.sending": { en: "Sending...", sw: "Inatuma..." },
  "contact.form.sendMsg": { en: "Send Message", sw: "Tuma Ujumbe" },
  "contact.form.success.title": { en: "Message Sent!", sw: "Ujumbe Umetumwa!" },
  "contact.form.success.desc": { en: "Thank you for contacting us. We'll get back to you soon.", sw: "Asante kwa kuwasiliana nasi. Tutakujibu hivi karibuni." },
  "contact.info.address": { en: "Address", sw: "Anwani" },
  "contact.info.phone": { en: "Phone", sw: "Simu" },
  "contact.info.email": { en: "Email", sw: "Barua Pepe" },
  "contact.info.hours": { en: "Office Hours", sw: "Masaa ya Ofisi" },
  "contact.follow": { en: "Follow Us", sw: "Tufuate" },
  "contact.findUs": { en: "Find Us", sw: "Tupate" },
  "contact.map.viewMapcarta": { en: "View location on Mapcarta", sw: "Tazama mahali kwenye Mapcarta" },

  // Gallery Page
  "gallery.hero.title": { en: "Photo Gallery", sw: "Jumba la Picha" },
  "gallery.hero.subtitle": { en: "Explore moments and memories from Sacred Heart Secondary School", sw: "Chunguza nyakati na kumbukumbu kutoka Shule ya Sekondari ya Sacred Heart" },
  "gallery.page.title": { en: "Our Gallery", sw: "Jumba Letu la Picha" },
  "gallery.page.subtitle": { en: "A visual journey through our school life, activities, and achievements", sw: "Safari ya kuona maisha ya shule, shughuli, na mafanikio yetu" },
  "gallery.featured": { en: "Featured", sw: "Iliyoangaziwa" },
  "gallery.noImages": { en: "No images found in this category.", sw: "Hakuna picha zilizopatikana katika kategoria hii." },
  "gallery.cat.all": { en: "All", sw: "Zote" },
  "gallery.cat.campus": { en: "Campus", sw: "Kampasi" },
  "gallery.cat.academics": { en: "Academics", sw: "Taaluma" },
  "gallery.cat.sports": { en: "Sports", sw: "Michezo" },
  "gallery.cat.facilities": { en: "Facilities", sw: "Vifaa" },
  "gallery.cat.events": { en: "Events", sw: "Matukio" },

  // Footer portal links
  "footer.student.portal": { en: "Student Portal", sw: "Lango la Mwanafunzi" },
  "footer.teacher.portal": { en: "Teacher Portal", sw: "Lango la Mwalimu" },
  "footer.parent.portal": { en: "Parent Portal", sw: "Lango la Mzazi" },
  "footer.system.online": { en: "System Online", sw: "Mfumo Umewashwa" },
  "footer.secure": { en: "Secure Connection", sw: "Muunganisho Salama" },
  "footer.nursery": { en: "SIIMA Nursery", sw: "Chekechea ya SIIMA" },
  "footer.primary": { en: "SIIMA Primary", sw: "Msingi ya SIIMA" },
  "footer.secondary": { en: "Sacred Heart Secondary", sw: "Sekondari ya Sacred Heart" },
  "admissions.table.item": { en: "Item", sw: "Kipengele" },
  "admissions.table.amount": { en: "Amount (TZS)", sw: "Kiasi (TZS)" },

  // News & Events Page
  "news.page.hero.subtitle": { en: "Stay updated with the latest happenings at Sacred Heart Secondary School", sw: "Endelea kupata habari za hivi karibuni zinazotokea Shule ya Sekondari ya Sacred Heart" },
  "news.page.latest": { en: "Latest News", sw: "Habari za Hivi Karibuni" },
  "news.page.latest.subtitle": { en: "Recent updates and announcements from our school community", sw: "Sasisho za hivi karibuni na matangazo kutoka kwa jumuiya ya shule yetu" },
  "news.page.noArticles": { en: "No news articles available.", sw: "Hakuna makala ya habari zilizopo." },
  "news.page.readMore": { en: "Read More", sw: "Soma Zaidi" },
  "news.page.upcoming": { en: "Upcoming Events", sw: "Matukio Yanayokuja" },
  "news.page.noEvents": { en: "No upcoming events.", sw: "Hakuna matukio yanayokuja." },
  "news.page.viewGallery": { en: "View Photo Gallery", sw: "Tazama Jumba la Picha" },
  "news.page.close": { en: "Close", sw: "Funga" },

  // Not Found Page
  "notfound.title": { en: "Oops! Page not found", sw: "Lo! Ukurasa haukupatikana" },
  "notfound.return": { en: "Return to Home", sw: "Rudi Nyumbani" },

  // Auth Page extras
  "auth.forgotPassword": { en: "Forgot Password", sw: "Umesahau Nenosiri" },
  "auth.resetPassword": { en: "Reset Password", sw: "Weka Upya Nenosiri" },
  "auth.forgotSubtitle": { en: "Enter your email to receive a password reset link", sw: "Ingiza barua pepe yako kupata kiungo cha kuweka upya nenosiri" },
  "auth.resetSubtitle": { en: "Enter your new password", sw: "Ingiza nenosiri lako jipya" },
  "auth.newPassword": { en: "New Password", sw: "Nenosiri Jipya" },
  "auth.confirmNewPassword": { en: "Confirm New Password", sw: "Thibitisha Nenosiri Jipya" },
  "auth.forgotPasswordQ": { en: "Forgot password?", sw: "Umesahau nenosiri?" },
  "auth.sendResetLink": { en: "Send Reset Link", sw: "Tuma Kiungo cha Kuweka Upya" },
  "auth.processing": { en: "Processing...", sw: "Inachakata..." },
  "auth.backToLogin": { en: "Back to Login", sw: "Rudi Kuingia" },
  "auth.backToHome": { en: "← Back to Homepage", sw: "← Rudi Ukurasa wa Nyumbani" },
  "auth.loginSubtitle": { en: "Sign in to your school account", sw: "Ingia kwenye akaunti yako ya shule" },
  "auth.portalLabel": { en: "Portal", sw: "Lango" },

  // Services Page
  "services.page.title": { en: "Our Services", sw: "Huduma Zetu" },
  "services.page.subtitle": { en: "Comprehensive educational services designed to nurture academic excellence and holistic development", sw: "Huduma kamili za elimu zilizoundwa kukuza ubora wa kitaaluma na maendeleo ya jumla" },
  "services.offer.title": { en: "What We Offer", sw: "Tunachotoa" },
  "services.offer.subtitle": { en: "Sacred Heart Secondary School provides a wide range of services to ensure every student receives quality education and support", sw: "Shule ya Sekondari ya Sacred Heart inatoa aina mbalimbali za huduma ili kuhakikisha kila mwanafunzi anapata elimu bora na msaada" },
  "services.quality.title": { en: "Quality Education", sw: "Elimu Bora" },
  "services.quality.desc": { en: "Comprehensive curriculum following NECTA standards with experienced teachers providing excellent academic foundation.", sw: "Mtaala kamili unaofuata viwango vya NECTA na walimu wenye uzoefu wanaotoa msingi bora wa kitaaluma." },
  "services.library.title": { en: "Library Services", sw: "Huduma za Maktaba" },
  "services.library.desc": { en: "Well-stocked library with thousands of books, digital resources, and quiet study spaces for research and learning.", sw: "Maktaba yenye vitabu vingi, rasilimali za kidijitali, na nafasi tulivu za kujisomea kwa utafiti na kujifunza." },
  "services.computer.title": { en: "Computer Training", sw: "Mafunzo ya Kompyuta" },
  "services.computer.desc": { en: "Modern computer labs with internet access, teaching digital literacy and programming skills for the modern world.", sw: "Maabara za kisasa za kompyuta zenye mtandao, zinazofundisha ujuzi wa kidijitali na upangaji programu." },
  "services.sports.title": { en: "Sports & Athletics", sw: "Michezo na Riadha" },
  "services.sports.desc": { en: "Complete sports program including football, basketball, volleyball, athletics, and other extracurricular activities.", sw: "Programu kamili ya michezo ikiwemo mpira wa miguu, mpira wa kikapu, mpira wa wavu, riadha, na shughuli nyingine za ziada." },
  "services.boarding.title": { en: "Boarding Facilities", sw: "Vifaa vya Bweni" },
  "services.boarding.desc": { en: "Comfortable dormitories with nutritious meals, 24/7 security, and conducive environment for academic excellence.", sw: "Mabweni ya starehe na chakula cha lishe, usalama wa saa 24/7, na mazingira wezeshi kwa ubora wa kitaaluma." },
  "services.transport.title": { en: "Transport Services", sw: "Huduma za Usafiri" },
  "services.transport.desc": { en: "Safe and reliable school bus service covering major routes in and around the city for day students.", sw: "Huduma salama na ya kuaminika ya basi la shule inayochukua njia kuu ndani na nje ya jiji kwa wanafunzi wa siku." },
  "services.counseling.title": { en: "Counseling Services", sw: "Huduma za Ushauri" },
  "services.counseling.desc": { en: "Professional guidance and counseling support for academic, career, and personal development matters.", sw: "Msaada wa kitaalamu wa mwongozo na ushauri kwa masuala ya kitaaluma, kazi, na maendeleo ya kibinafsi." },
  "services.health.title": { en: "Health Services", sw: "Huduma za Afya" },
  "services.health.desc": { en: "On-site dispensary with qualified nurse, first aid facilities, and health education programs for all students.", sw: "Zahanati ya ndani na muuguzi aliyehitimu, vifaa vya msaada wa kwanza, na programu za elimu ya afya kwa wanafunzi wote." },
  "services.cta.title": { en: "Ready to Join Sacred Heart?", sw: "Uko Tayari Kujiunga na Sacred Heart?" },
  "services.cta.desc": { en: "Experience the difference of quality education. Apply now and become part of our growing family of scholars.", sw: "Pata tofauti ya elimu bora. Omba sasa na uwe sehemu ya familia yetu inayokua ya wasomi." },
  "services.cta.button": { en: "Apply for Admission", sw: "Omba Usajili" },

  // Hero / School tagline
  "hero.tagline": { en: "Education Is The Way Up", sw: "Elimu Ndiyo Njia Juu" },

  // Students Page
  "students.page.title": { en: "Students", sw: "Wanafunzi" },
  "students.page.subtitle": { en: "Discover the vibrant student life and opportunities at Sacred Heart Secondary School", sw: "Gundua maisha ya kuvutia ya wanafunzi na fursa katika Shule ya Sekondari ya Sacred Heart" },
  "students.stat.total": { en: "Total Students", sw: "Jumla ya Wanafunzi" },
  "students.stat.form14": { en: "Form 1-4", sw: "Kidato cha 1-4" },
  "students.stat.form56": { en: "Form 5-6", sw: "Kidato cha 5-6" },
  "students.stat.boarders": { en: "Boarders", sw: "Wanafunzi wa Bweni" },
  "students.life.title": { en: "Student Life", sw: "Maisha ya Mwanafunzi" },
  "students.life.subtitle": { en: "Beyond the classroom, students engage in various activities that shape character and build skills", sw: "Zaidi ya darasa, wanafunzi wanashiriki katika shughuli mbalimbali zinazounda tabia na kujenga ujuzi" },
  "students.life.clubs.title": { en: "Academic Clubs", sw: "Klabu za Kitaaluma" },
  "students.life.clubs.desc": { en: "Debate, Science, Mathematics, and Literature clubs for intellectual growth", sw: "Klabu za Mdahalo, Sayansi, Hisabati, na Fasihi kwa ukuaji wa kiakili" },
  "students.life.sports.title": { en: "Sports Teams", sw: "Timu za Michezo" },
  "students.life.sports.desc": { en: "Football, Basketball, Volleyball, Athletics and more competitive sports", sw: "Mpira wa miguu, mpira wa kikapu, mpira wa wavu, riadha na michezo mingine ya mashindano" },
  "students.life.service.title": { en: "Community Service", sw: "Huduma kwa Jamii" },
  "students.life.service.desc": { en: "Volunteer programs teaching social responsibility and compassion", sw: "Programu za kujitolea zinazofundisha wajibu wa kijamii na huruma" },
  "students.life.arts.title": { en: "Arts & Culture", sw: "Sanaa na Utamaduni" },
  "students.life.arts.desc": { en: "Music, Drama, Dance, and Traditional Cultural groups", sw: "Muziki, Tamthilia, Ngoma, na vikundi vya Utamaduni wa Jadi" },
  "students.leaders.title": { en: "Student Leadership", sw: "Uongozi wa Wanafunzi" },
  "students.leaders.subtitle": { en: "Meet our student government leaders who represent the student body", sw: "Kutana na viongozi wetu wa serikali ya wanafunzi wanaowakilisha wanafunzi" },
  "students.achievements.title": { en: "Student Achievements", sw: "Mafanikio ya Wanafunzi" },
  "students.achievements.subtitle": { en: "Celebrating the success of our students in various competitions", sw: "Kusherehekea mafanikio ya wanafunzi wetu katika mashindano mbalimbali" },
  "students.portal.title": { en: "Student Portal", sw: "Lango la Mwanafunzi" },
  "students.portal.desc": { en: "Access your grades, assignments, timetable, and more through the student portal.", sw: "Fikia alama zako, kazi za nyumbani, ratiba ya masomo, na zaidi kupitia lango la mwanafunzi." },
  "students.portal.button": { en: "Go to Student Portal", sw: "Nenda Lango la Mwanafunzi" },

  // Student leader positions
  "life.headGirl": { en: "Head Girl", sw: "Kiongozi Msichana Mkuu" },
  "life.headBoy": { en: "Head Boy", sw: "Kiongozi Mvulana Mkuu" },
  "life.academicPrefect": { en: "Academic Prefect", sw: "Prefekti wa Masomo" },
  "life.sportsCapt": { en: "Sports Captain", sw: "Kapteni wa Michezo" },

  // Results Chart (2015-2024)
  "results.chart.badge": { en: "Academic Growth", sw: "Ukuaji wa Kitaaluma" },
  "results.chart.title": { en: "A Decade of", sw: "Miongo ya" },
  "results.chart.excellence": { en: "Excellence", sw: "Ubora" },
  "results.chart.desc": { en: "Since 2015, Sacred Heart Secondary has maintained a trajectory of consistent improvement, culminating in a perfect 100% pass rate in 2024.", sw: "Tangu mwaka 2015, Sekondari ya Sacred Heart imedumisha mwelekeo wa kuboresha mfululizo, ikifikia kiwango bora cha kafaulu cha 100% mwaka 2024." },
  "results.chart.currentRate": { en: "Current Pass Rate", sw: "Kiwango cha Sasa cha Kufaulu" },
  "results.chart.distinctionRate": { en: "Distinction Rate", sw: "Kiwango cha Sifa (Distinction)" },
  "results.chart.viewCertificates": { en: "View all official NECTA certificates", sw: "Tazama vyeti vyote rasmi vya NECTA" },
  "results.chart.passRateLabel": { en: "Passing Rate (2015 - 2024)", sw: "Kiwango cha Kufaulu (2015 - 2024)" },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    return translation[language];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
